spring.application.name=qashqade
server.port=8080

# -- JPA / Hibernate -------------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=qashqade
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Active profile -- override with -Dspring.profiles.active=prod in Kubernetes
spring.profiles.active=dev
